management.endpoints.web.exposure.include=health,prometheus
management.metrics.tags.application=coin-zzickmock
management.metrics.tags.service=backend
management.metrics.tags.environment=${APP_ENV:local}
