export const futuresQueryKeys = {
  account: ["futures", "account"] as const,
  refillStatus: ["futures", "account", "refill"] as const,
  walletHistory: ["futures", "account", "wallet-history"] as const,
  positions: ["futures", "positions"] as const,
  openOrders: ["futures", "orders", "open"] as const,
  orderHistory: ["futures", "history", "orders"] as const,
  positionHistory: ["futures", "history", "positions"] as const,
  reward: ["futures", "reward"] as const,
  leaderboard: ["futures", "leaderboard"] as const,
  shopItems: ["shop", "items"] as const,
  shopMe: ["shop", "me"] as const,
  rewardHistory: ["futures", "reward", "history"] as const,
  rewardRedemptions: ["shop", "redemptions"] as const,
  rewardShopHistory: ["shop", "history"] as const,
  admin: ["admin"] as const,
  community: ["community"] as const,
};

export const personalizedQueryKeyPrefixes = [
  futuresQueryKeys.account,
  futuresQueryKeys.refillStatus,
  futuresQueryKeys.walletHistory,
  futuresQueryKeys.positions,
  futuresQueryKeys.openOrders,
  futuresQueryKeys.orderHistory,
  futuresQueryKeys.positionHistory,
  futuresQueryKeys.reward,
  futuresQueryKeys.leaderboard,
  futuresQueryKeys.shopMe,
  futuresQueryKeys.rewardHistory,
  futuresQueryKeys.rewardRedemptions,
  futuresQueryKeys.rewardShopHistory,
  futuresQueryKeys.admin,
  futuresQueryKeys.community,
] as const;
